version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: chohan_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html/frontend_chohan
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
      - php
    networks:
      - app-network

  php:
    image: php:8.0-fpm
    container_name: chohan_php
    working_dir: /var/www/html
    command: "php -S 0.0.0.0:80"
    volumes:
      - ./landing_chohan:/var/www/html
    networks:
      - app-network

  frontend:
    image: node:18-alpine
    container_name: chohan_frontend
    working_dir: /app
    volumes:
      - ./frontend_chohan:/app
      - ./dist:/app/dist
    command: sh -c "npm install --legacy-peer-deps && npm run build"
    networks:
      - app-network

  backend:
    image: node:18-alpine
    container_name: chohan_backend
    working_dir: /api
    volumes:
      - ./api_chohan:/api
    command: sh -c "apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont && npm install && npm start"
    ports:
      - "5000:5000"
    env_file:
      - ./api_chohan/.env
    networks:
      - app-network

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./mssql:/var/opt/mssql
      - ./mssql_init:/tmp
      - ./dbbackup:/var/opt/mssql/dbbackup

networks:
  app-network:
    driver: bridge
