<!DOCTYPE html>
<html lang="en-US">
<head>
<?php include("top.php");?>
</head>
<body class="home page-template page-template-elementor_header_footer page page-id-6 jkit-color-scheme elementor-default elementor-template-full-width elementor-kit-3 elementor-page elementor-page-6">
<?php include("svg.php");?>
<div id="page" class="jkit-template  site">
<?php include("header.php");?>
<div data-elementor-type="wp-page" data-elementor-id="6" class="elementor elementor-6">
<?php include("slider.php");?>
<?php //include("search.php");?>
<?php include("home_about.php");?>
<?php include("home_service.php");?>
<?php //include("home_download_shuttle_app.php");?>
<?php include("home_our_bus_collection.php");?>		
<?php include("home_testimonial.php");?>
<?php include("home_blog.php");?>
</div>
<?php include("footer_above.php");?>
</div>
<!-- #page -->
<?php include("footer.php");?>
<div class="anima_dk1">
<a target="_blank" href="https://api.whatsapp.com/send?phone=919836000999"><img src="images/whatapp_icon.png"></a>
</div>
<style>

.anima_dk1 {
    position: fixed;
    bottom:50px;
    left: 15px;
    z-index: 9;
    padding: 4px;
    border-radius: 5px;
}
</style>
</body>
</html>
<!-- Dynamic page generated in 2.110 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2022-07-14 03:17:48 -->
<!-- super cache -->